# Generated by Django 4.0.1 on 2022-01-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2_MM_MLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('decimal_date', models.DecimalField(decimal_places=4, max_digits=10)),
                ('average', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interpolated', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
